name: baby_sleep_scheduler
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter: { sdk: flutter }
  intl:
  path: any
  path_provider_macos: ^0.0.1
  shared_preferences: ^2.0.0
  sqflite: ^1.3.2+1
  #  flutter_local_notifications: ^3.0.3
  flutter_local_notifications: ^16.3.0
  flutter_native_timezone: ^1.0.4
  url_launcher: any
  flutter_linkify: ^5.0.2
  equatable: ^2.0.5
  flutter_gen: ^5.3.2
  provider: ^6.1.1
  charts_flutter:
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter
  wakelock: any
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald.ttf
flutter_gen:
  assets:
    - lib/l10n/intl_en.arb
flutter_intl:
  enabled: true
